name: fasolingo
description: "LinguaLearn - Application d’apprentissage des langues"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # UI & Animation
  lottie: ^2.7.0
  confetti: ^0.7.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1

  # State Management
  get: ^4.6.6
  provider: ^6.0.5
  get_storage: ^2.1.1
  shared_preferences: ^2.2.0

  # Network
  dio: ^5.5.0+1
  http: ^1.4.0
  logger: ^2.3.0

  # Device & Media
  image_picker: ^1.0.0
  file_picker: ^10.0.0
  device_info_plus: ^10.1.2

  # Notifications
  flutter_local_notifications: ^17.2.2

  # WebSocket
  stomp_dart_client: ^2.0.0
  web_socket_channel: ^3.0.1

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.1.11
  url_strategy: ^0.2.0
  lucide_icons: ^0.257.0

  # Icons
  cupertino_icons: ^1.0.6

  # Splash & Launcher
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/images/logo/login.png

  android: true
  ios: true
  ios_content_mode: scaleAspectFit
  web: false

  android_12:
    image: assets/images/logo/login.png
    icon_background_color: "#ffffff"
    fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/login.png"

  web:
    generate: true
    image_path: "assets/images/logo/login.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

  windows:
    generate: true
    image_path: "assets/images/logo/login.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/images/logo/login.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/logo/
    - assets/images/app/
    - assets/images/quiz/
    - assets/icon/
    - assets/avatar/
    - assets/lottie/
    - assets/img/8e4b0793efdb04971f43cf916a5f151e.jpg

dependency_overrides:
  image_picker_linux: any
  shared_preferences_linux: any